name: postgres
dependencies:
  - jupyter==1.0.0
  - numpy==1.18.5
  - pandas==1.0.5
  - pip
  - pip:
      - -e .  # executes setup.py -> 'src' becomes a (local) package
      - psycopg2==2.8.6
      - python-dotenv==0.15.0
